### ISSUE TITLE
Columns are not required for HTML

### ISSUE THREAD

**Issue by Redmayspecial** [Bible-Translation-Tools/USFM-Converter#35]
Columns are required for DOCX but not for HTML.

**Comment by Thundelly** [comment]
DOCX 

![image](https://user-images.githubusercontent.com/37914691/124313034-2969bb00-db25-11eb-9669-f96923891e0b.png)

HTML
![image](https://user-images.githubusercontent.com/37914691/124313610-f07e1600-db25-11eb-878a-44ed041bb938.png)
